### ISSUE TITLE
Project Setup Tasks

### ISSUE THREAD

**Issue by DocOtak** [DocOtak/gsw-xarray#1]
Some tasks which need to get done just to get the project "going".

- [x] #7
- [ ] Code cleanliness things
  - [ ] Pre-commit
  - [ ] black
- [x] Actual tests
- [x] #2

Slightly harder to figure out are project feature goals, some ideas for now...:
* Add a Dataset accessor which automatically discovers standard names and what parameters can be derived from them.
  * This is a little tricky due to gsw wanting inputs using specific units. (Do we rely on pint?)
* Decisions about what other attributes to override/remove when doing a conversion

**Comment by rcaneill** [comment]
Nice to ping on this project! I think that having a simple but efficient tool as starting point is a good beginning. Whenever this will work, start on a more complex Dataset accessor.

Depending on your preferences, I can either: 1) start writing some tests, or 2) reshape the code to a clean organization.

**Comment by DocOtak** [comment]
@rcaneill Hopefully I've added you as someone who can commit to this repo (let me know if you cannot).

I agree with your approach of having something simple before attempting an accessor. What do you have in mind for code organization?

Some of my own preferences as we get started:
* I'd like to continue the use of poetry for now, I've heard very good things about it and I'm evaluating if I want to switch other projects over to it.
* pytest for the tests
* It might be neat to include some real world oceanographic data files (e.g. Argo) as part of the tests (maybe as part of doctests?).
* I really like the ability to be able to test the installed module so I tend to keep tests inside the source rather than along side it. The actual test machinery (e.g. pytest) can be optional dependencies.
* At some point switch to [setuptools-scm](https://github.com/pypa/setuptools_scm/) for the versioning.
* Re ecosystem compatibility, lets target the same as xarray, so [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), for when things like CI are setup.

**Comment by rcaneill** [comment]
By code organization I meant reorganizing what you already wrote into a cleaner solution that is not only contained in the __init__.py file (maybe a file containing the `_func_standard_name_units` tuple, another for the main function, and later on another for the accessor). Does it make sense to you to split the files like this?

I never used poetry, so I am happy to discover it.
I agree with the rest.

**Comment by DocOtak** [comment]
That code re-organization sounds fine, please have at it 😉 (that is, I won't attempt any conflicting code changes until I see a reorg). I'll get a docs (sphinx etc..) scaffold setup in the next few days, which should be independent of anything going on in the code source dir.

Right now this module is an xarray aware drop in replacement for gsw in that it will fall back to default gsw if we aren't wrapping the function (see the magic  PEP 562 dunder methods at the bottom of the __init__.py). My feeling is that this would be super useful to retain in that it allows you to not worry about which module to import a function from.

If poetry doesn't work out, we can drop it.

**Comment by rcaneill** [comment]
Another point that comes into my mind (I'll be the 1st happy to use it :p):
* [ ] Add a short contributor guide (how to git clone, install the environment, install the package, etc)

**Comment by rcaneill** [comment]
Should we agree on a working method? I propose that before resolving a bug or adding a feature, someone open an issue describing the bug / new feature, assign himself in the github Assignees, and submit a PR whenever the code is ready. This way (almost) all PR will be linked to a precise issue, and we limit the possibilities of duplicate work or you and me having the same idea at the same time and implementing it twice.
I am not sure if this is a common practice, but it feels to me to be a good working method.

**Comment by DocOtak** [comment]
I agree with the Issue then PR workflow. Also usual "best practice" for collaborative projects like this is at least one other person "approves" a PR (but you can self merge after approval).

**Comment by rcaneill** [comment]
I was thinking of a feature that would be nice to have (in a short / long term future): being able to give a dataset `ds` to the gsw wrapped functions, and gsw-xarray would then get from `ds` the necessary dataarrays, based on their standard_name. So one could use: `gsw.sigma0(ds)`. This can lead to many problems (e.g. how to deal with datasets containing more than 1 array for 1 standard_name), but we can keep the discussion on how to solve these problems for later, if we decide to implement this feature.

**Comment by rcaneill** [comment]
Another nice feature would be to add a `dim` argument for functions needing the `axis` argument, and then transform it to the proper axis, e.g. use `gsw.Nsquared(ds.SA, ds.CT, ds.p, lat=None, dim='depth')`
