### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#11]
Actually there is no license, which is problematic.
For me, any license would fit, gsw seems to be a BSD like license, xarray is Apache license 2.0, I use often the MIT license.

**Comment by DocOtak** [comment]
I almost always use a [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause), for "COPYRIGHT HOLDER" we can do "gsw-xarray contributors".

Lets also add your name in various places that currently only have my name (docs, pypi, etc..)
