### ISSUE TITLE
CI testing / black (?) / flake8 / isort (?)

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#13]
We should use the github actions to have a CI for the tests.

We can discuss whether to format the code with black (common within xarray community), verify with flake8 the coding style, and use isort to automatically sort the imports.

**Comment by rcaneill** [comment]
(This is maybe not urgent for the v0.2.0, we could keep it for later. If you think that it is essential, I let you add this issue to the milestone version 0.2.0)

**Comment by rcaneill** [comment]
CI with test done in PR #15, so what is left is black / flake8 / isort

**Comment by DocOtak** [comment]
Pre-commit + CI checks for style/black? I've never used isort, but did see when xarray was first adding it, they excluded it from the normal CI checks and just manually ran it occasionally. Not sure what the current status over there is.
