### ISSUE TITLE
Remove version capping?

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#16]
Should we keep the upper bound version constraint in the pyproject.toml? It seems a bad idea to use this restriction, unless there is a special reason I am not aware of.

 [Cf this post](https://iscinumpy.dev/post/bound-version-constraints/).

**Comment by DocOtak** [comment]
We can probably relax this, xarray is switching to calver soon and I suspect the current way this is setup would not by happy with that.
