### ISSUE TITLE
Add Contributor Guide for how to get started.

### ISSUE THREAD

**Issue by DocOtak** [DocOtak/gsw-xarray#3]
Another point that comes into my mind (I'll be the 1st happy to use it :p):
* [ ] Add a short contributor guide (how to git clone, install the environment, install the package, etc)

_Originally posted by @rcaneill in https://github.com/DocOtak/gsw-xarray/issues/1#issuecomment-1020935497_

**Comment by rcaneill** [comment]
I can work on a minimal guide to add in the readme (we can move this to the doc when they are ready).

**Comment by DocOtak** [comment]
Closed by #8
