### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by DocOtak** [DocOtak/gsw-xarray#37]
I think I will defer the automated machinery for now and just do this one manually.

The todo list
- [x] Update version refs to be "0.2.0"
- [x] Add a change log
- [x] Git tag (using the release mechanism on github)
- [x] Upload artifacts to pypi
- [ ] Release Party?

**Comment by rcaneill** [comment]
Could you also add the link to the doc in the github short description of the reposirory?

**Comment by DocOtak** [comment]
Released! (That party is optional)

**Comment by rcaneill** [comment]
I'll celebrate it!
![](https://c.tenor.com/c86D6_XlACMAAAAM/weekend-party.gif)
