### ISSUE TITLE
Publish on conda-forge?

### ISSUE THREAD

**Issue by DocOtak** [DocOtak/gsw-xarray#43]
While have never used it myself, I'm aware that conda-forge is a very popular place to get python packages.

It would probably be a good benefit to the community if we figure out how to get this package published on conda-forge.

**Comment by rcaneill** [comment]
I totally agree with you, I have never done it but it should not be too complicated

**Comment by rcaneill** [comment]
I started to create the recipe for conda-forge, see [https://github.com/rcaneill/staged-recipes/blob/gsw-xarray/recipes/gsw-xarray/meta.yaml](https://github.com/rcaneill/staged-recipes/blob/gsw-xarray/recipes/gsw-xarray/meta.yaml)

I'll try to comment on this issue with the steps needed to create the recipe (and maybe how to make it automatic via github actions when releasing?)

**Comment by DocOtak** [comment]
Awesome, feel free to commit the master/main branch here if you feel things are ready (or if you need to experiment).

**Comment by rcaneill** [comment]
PR opened https://github.com/conda-forge/staged-recipes/pull/18775

**Comment by DocOtak** [comment]
Does the build on/for conda-forge fail without that "use deprecated out of tree build" option?

**Comment by rcaneill** [comment]
I don't know, I commit the change Daniel Ching proposed, we'll see if this builds. I also asked him if the option is necessary

**Comment by rcaneill** [comment]
> Does the build on/for conda-forge fail without that "use deprecated out of tree build" option?

Answer from the conda-forge team:

https://github.com/conda-forge/staged-recipes/pull/18775#issuecomment-1121331047
> Yes, this is the current recommendation for packages that use poetry for build until conda-build is patched. I believe that without this arg, poetry will try and create its own build environment which is not what we want / is redundant.
> Related: https://github.com/conda-forge/conda-forge.github.io/pull/1540

**Comment by DocOtak** [comment]
@rcaneill I'm seeing some emails suggesting this is/has happened! Awesome stuff! Thanks so much!

**Comment by rcaneill** [comment]
It seems that there is still a little problem... I'll try to fix it / get some help

**Comment by rcaneill** [comment]
We are now on conda-forge!

https://anaconda.org/conda-forge/gsw-xarray
