### ISSUE TITLE
Update documentation to include what input Quantities are expected when using Pint

### ISSUE THREAD

**Issue by DocOtak** [DocOtak/gsw-xarray#51]
Now that pint support has landed, the expected inputs should be documented on that big long list of functions with the attribute outputs.

I'd like to evaluate switching to the py:func sphinx domain for these functions.

**Comment by DocOtak** [comment]
@rcaneill do we have any lingering concerns about pint support? Is https://github.com/TEOS-10/GSW-Python/issues/97 an issue for how we did pint support? do we need to revert back to positional arguments when finally calling the upstream functions?

**Comment by rcaneill** [comment]
I already implemented the reversion back to positional / keyword arguments when calling the upstream function: https://github.com/DocOtak/gsw-xarray/blob/ff552ddc271a7387fa66068839d6f83a1327d490/gsw_xarray/_core.py#L138-L141
I think this was done in PR #47 (hence closing issue #49)

So we don't have any problems

**Comment by DocOtak** [comment]
Oof, yep, failure on my part to notice that. 😞 

I'll work on this issues (#51) and on some automated release stuff so we can release when things are tagged on GH. I'll probably use https://test.pypi.org/ while getting this set up.

**Comment by rcaneill** [comment]
> I'll work on this issues (#51) and on some automated release stuff so we can release when things are tagged on GH. I'll probably use https://test.pypi.org/ while getting this set up.

Great! I wanting to do it but never got time...

**Comment by DocOtak** [comment]
Every time I think I'll have time to work on this... I seem to get delayed. Well I made sure to have some time today.

* Docs are updated with expected input units: https://gsw-xarray.readthedocs.io/en/latest/attrs.html
* An automatic publisher is setup to publish on tag (or manually), I tested it with the test.pypi site everything seems good to go.
* Not related to publishing, but I was convinced/persuaded to give a small talk about this project to the [ESIP Marin Data Cluster](https://wiki.esipfed.org/MarineData). I've included the jupyter notebook I used in an examples directory.

Other than doing the actual "release", is there anything else blocking 0.3.0?

**Comment by rcaneill** [comment]
Great news! I think that the only thing missing before releasing is changing the changelog.
Thanks for your great work :)

**Comment by DocOtak** [comment]
Awesome, great catch.


Here we go! 🤞

**Comment by DocOtak** [comment]
Looks to be... not broken!

How do we update the conda forge version?

**Comment by DocOtak** [comment]
I guess we just approve the PR made by the robot?

**Comment by rcaneill** [comment]
Yes I think so
