### ISSUE TITLE
We forgot to change version in __init__.py file

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#62]
Version is still 0.2.1
I guess we just need to take care to update it next time

**Comment by DocOtak** [comment]
Oops, we should change this to using the `version` function from `importlib.metadata`.

```python
from importlib.metadata import version
__version__ = version("gsw_xarray")
```

Probably with a fallback for funny install situations (i.e. dev)

**Comment by rcaneill** [comment]
https://github.com/python-poetry/poetry/issues/144#issuecomment-623927302

There seems to be an easy solution for the dev
