### ISSUE TITLE
pint does not parse well unit with exponents

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#63]
Some units consists of multiple set of parenthesis, with exponents -1 (e.g. next line). However they are not parsed correctly by pint.
https://github.com/DocOtak/gsw-xarray/blob/08a13415e0993ae2b76991d956b569c239d842a6/gsw_xarray/_attributes.py#L651

```python
import cf_xarray.units  # must be imported before pint_xarray
import pint_xarray
from pint_xarray import unit_registry as ureg

ureg('(kg/m^3)*(g/kg)^-1')
```
outputs (what we want):
```
1.0 kilogram2/(gram meter3)
```

but without the star
```python
ureg('(kg/m^3)(g/kg)^-1')
```
output
```
1.0 meter3/gram
```

I opened an issue in pint about this: https://github.com/hgrecco/pint/issues/1730. In the meantime, we should replace these unit with either a '*' between the parenthesis, or with an extra set of parenthesis.
Any opinion on which solution we should implement?

**Comment by dcherian** [comment]
cc @keewis @aulemahal

**Comment by DocOtak** [comment]
Maybe `(kg/m^3)/(g/kg)` and just avoid the exponent?

udunits2 thinks all these options are equal to `1000 m^-3 kg` i.e. cancels the g/kg to scaling constant.

**Comment by rcaneill** [comment]
So I confirm that this is an issue from pint, that was already described (https://github.com/hgrecco/pint/issues/1485). The take home message for us is that we should not use parenthesis without the `*` sign outside of them.
