### ISSUE TITLE
Add a word on the gsw / xarray doc

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#9]
* [x] Whenever a working version will be ready, one should add a sentence in the official gsw doc so users know that they can use the gsw_xarray wrapper for xarray.
* [x] We can also add it on the [xarray doc, ecosystem](https://xarray.pydata.org/en/stable/ecosystem.html).

**Comment by DocOtak** [comment]
Awesome, I was wondering how the xarray/pangeo folks found this already.
